services:
  comfyui-worker:
    image: worker-comfyui:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HUGGINGFACE_ACCESS_TOKEN=${HUGGINGFACE_ACCESS_TOKEN}
        - CIVITAI_TOKEN=${CIVITAI_TOKEN}
        - LORAS_IDS_TO_DOWNLOAD=${LORAS_IDS_TO_DOWNLOAD}
        - CHECKPOINT_IDS_TO_DOWNLOAD=${CHECKPOINT_IDS_TO_DOWNLOAD}
        - MODEL_TYPE=${MODEL_TYPE}
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
